-- MIGRATION & SETUP COMMANDS (Run these in Supabase SQL Editor)

-- 1. Create Suppliers table
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_name TEXT NOT NULL,
  phone_number TEXT,
  email TEXT,
  address TEXT,
  gst_number TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_no TEXT UNIQUE NOT NULL,
  product_group TEXT,
  product_name TEXT NOT NULL,
  supplier_id BIGINT REFERENCES suppliers(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Customers table (for the Directory)
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor TEXT NOT NULL,
  product_group TEXT,
  product_name TEXT,
  product_id BIGINT REFERENCES products(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Stock table
CREATE TABLE IF NOT EXISTS stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_no TEXT UNIQUE NOT NULL,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT,
  stock_quantity INTEGER DEFAULT 0,
  order_date TEXT,
  volume REAL,
  base_price REAL,
  has_gst INTEGER DEFAULT 0,
  total_price REAL,
  price_per_litre REAL,
  bill_type TEXT CHECK (bill_type IN ('Paid', 'Not Paid')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Sales table
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id),
  vendor TEXT NOT NULL,
  product_name TEXT,
  bill_type TEXT CHECK (bill_type IN ('Paid', 'Not Paid')),
  quantity INTEGER DEFAULT 0,
  delivery_notes TEXT,
  amount_status TEXT,
  payment_received_date TEXT,
  amount REAL,
  volume REAL,
  other_price REAL DEFAULT 0,
  total_price REAL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create Users table (for custom auth)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Refresh the Supabase API cache
NOTIFY pgrst, 'reload schema';

-- Note: Since we are using the service_role key from the backend, 
-- RLS (Row Level Security) is bypassed. If you want to use client-side 
-- Supabase calls, you will need to enable RLS and set up policies.
